application: avsm-01
version: 1
runtime: python
api_version: 1

handlers:
- url: /tasks/.*
  script: django_bootstrap.py
  login: admin
- url: /update/.*
  script: django_bootstrap.py
  secure: always
- url: .*
  script: django_bootstrap.py
  login: admin
  secure: always
